//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientodeNotaperiodisticas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Usuario
    {
        public int Id_TipoUsuario { get; set; }
        public string Tipo_usuario { get; set; }
        public int UsuarioUSR_idusuario { get; set; }
        public int UsuarioUSR_idusuario1 { get; set; }
    }
}
