//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientodeNotaperiodisticas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Tipo_Usuario = new HashSet<Tipo_Usuario>();
        }
    
        public int USR_idusuario { get; set; }
        public string USR_Username { get; set; }
        public string USR_Pass { get; set; }
        public int USR_Id_TipoUsuario { get; set; }
        public int Tipo_UsuarioId_TipoUsuario { get; set; }
    
        public virtual ICollection<Tipo_Usuario> Tipo_Usuario { get; set; }
    }
}
